### ISSUE TITLE
Can't run games

### ISSUE THREAD

**Issue by TaraSophieDev** [aksiksi/gbc#5]
So when I use the terminal and start gbcemu with that command + path [.\gbcemu.exe opus5.gb] it gives me an error like this "Found argument 'opus5.gb' which wasn't expected, or isn't valid in this context"

The game is in the same folder. Is there a right way to put this argument in?

**Comment by aksiksi** [comment]
Thanks for trying it out!

There is a `run` subcommand, so you actually need to run it like this:

```
./gbcemu.exe run opus5.gb
```

**Comment by TaraSophieDev** [comment]
thx it worked, how can I test it during development. 
`cargo run opus5.gb?`

**Comment by aksiksi** [comment]
You need to add a `--` to split between cargo arguments and binary arguments.

To run it in debug mode:

```
cargo run -- run opus5.gb
```

To run it in release mode:

```
cargo run --release -- run opus5.gb
```
